apiVersion: v1
kind: Namespace
metadata:
  name: sentinelops
  labels:
    app.kubernetes.io/part-of: sentinelops-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-demo
  labels:
    app.kubernetes.io/part-of: sentinelops-demo
