"""initial_baseline_schema

Revision ID: 0001_initial_baseline
Revises: None
Create Date: 2026-09-11 23:45:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute('CREATE TABLE IF NOT EXISTS anomaly_patterns (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tpattern_type VARCHAR(64) NOT NULL, \n\tservice_name VARCHAR(256) NOT NULL, \n\tpattern_data_json TEXT NOT NULL, \n\toccurrence_count INTEGER NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\tlast_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_anomaly_patterns_cluster_id ON anomaly_patterns (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_anomaly_patterns_pattern_type ON anomaly_patterns (pattern_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_anomaly_patterns_service_name ON anomaly_patterns (service_name);')
    op.execute('CREATE TABLE IF NOT EXISTS clusters (\n\tid UUID NOT NULL, \n\tname VARCHAR(128) NOT NULL, \n\tapi_server VARCHAR(512), \n\tcontext VARCHAR(256), \n\tstatus VARCHAR(32) NOT NULL, \n\tmetadata_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n);')
    op.execute('CREATE TABLE IF NOT EXISTS correlation_groups (\n\tid UUID NOT NULL, \n\tincident_id UUID, \n\tcluster_id UUID NOT NULL, \n\tnamespace VARCHAR(128) NOT NULL, \n\ttrigger VARCHAR(64) NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\tevent_count INTEGER NOT NULL, \n\trelated_event_ids_json TEXT, \n\tdependency_context_json TEXT, \n\tconfidence_score FLOAT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_correlation_groups_cluster_id ON correlation_groups (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_correlation_groups_incident_id ON correlation_groups (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS dependency_edges (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tsource_namespace VARCHAR(128) NOT NULL, \n\tsource_name VARCHAR(253) NOT NULL, \n\tsource_kind VARCHAR(64) NOT NULL, \n\ttarget_namespace VARCHAR(128) NOT NULL, \n\ttarget_name VARCHAR(253) NOT NULL, \n\ttarget_kind VARCHAR(64) NOT NULL, \n\tedge_type VARCHAR(64) NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\tdiscovery_method VARCHAR(64) NOT NULL, \n\tmetadata_json TEXT, \n\tdiscovered_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_dependency_edges_cluster_id ON dependency_edges (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS dependency_scores (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tsource_node_id VARCHAR(512) NOT NULL, \n\ttarget_node_id VARCHAR(512) NOT NULL, \n\tinfluence_score FLOAT NOT NULL, \n\tblast_radius INTEGER NOT NULL, \n\tpropagation_depth INTEGER NOT NULL, \n\tlast_updated TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_dependency_scores_target_node_id ON dependency_scores (target_node_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_dependency_scores_cluster_id ON dependency_scores (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_dependency_scores_source_node_id ON dependency_scores (source_node_id);')
    op.execute('CREATE TABLE IF NOT EXISTS infrastructure_memory (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tmemory_type VARCHAR(64) NOT NULL, \n\tkey VARCHAR(512) NOT NULL, \n\tvalue_json TEXT NOT NULL, \n\tsource_incident_id UUID, \n\tconfidence FLOAT NOT NULL, \n\tlast_updated TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_memory_memory_type ON infrastructure_memory (memory_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_memory_key ON infrastructure_memory (key);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_memory_cluster_id ON infrastructure_memory (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS services (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tnamespace VARCHAR(128) NOT NULL, \n\tname VARCHAR(253) NOT NULL, \n\tservice_type VARCHAR(32) NOT NULL, \n\tselector_json TEXT, \n\tports_json TEXT, \n\tlabels_json TEXT, \n\thealth_status VARCHAR(32) NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_services_namespace ON services (namespace);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_services_cluster_id ON services (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_services_name ON services (name);')
    op.execute('CREATE TABLE IF NOT EXISTS topology_snapshots (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tsnapshot_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tgraph_json TEXT NOT NULL, \n\tnode_count INTEGER NOT NULL, \n\tedge_count INTEGER NOT NULL, \n\tincident_id UUID, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_snapshots_snapshot_at ON topology_snapshots (snapshot_at);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_snapshots_cluster_id ON topology_snapshots (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_snapshots_incident_id ON topology_snapshots (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS topology_versions (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tversion INTEGER NOT NULL, \n\tsnapshot_id UUID, \n\tgraph_json TEXT NOT NULL, \n\tdiff_json TEXT, \n\tnode_count INTEGER NOT NULL, \n\tedge_count INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_versions_cluster_id ON topology_versions (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_versions_snapshot_id ON topology_versions (snapshot_id);')
    op.execute('CREATE TABLE IF NOT EXISTS executive_metrics (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tmttr_seconds FLOAT NOT NULL, \n\tmttd_seconds FLOAT NOT NULL, \n\tincident_frequency_per_day FLOAT NOT NULL, \n\tuptime_percent FLOAT NOT NULL, \n\tsla_compliance_percent FLOAT NOT NULL, \n\tpredicted_uptime_24h FLOAT NOT NULL, \n\tpredicted_incidents_24h INTEGER NOT NULL, \n\treliability_score FLOAT NOT NULL, \n\toperational_efficiency_score FLOAT NOT NULL, \n\tcalculated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_executive_metrics_cluster_id ON executive_metrics (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_executive_metrics_calculated_at ON executive_metrics (calculated_at);')
    op.execute('CREATE TABLE IF NOT EXISTS incident_forecasts (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tforecast_type VARCHAR(64) NOT NULL, \n\ttarget_service VARCHAR(253) NOT NULL, \n\ttarget_pod VARCHAR(253), \n\tprobability FLOAT NOT NULL, \n\tconfidence_score FLOAT NOT NULL, \n\tseverity_prediction VARCHAR(32) NOT NULL, \n\tforecast_horizon_seconds INTEGER NOT NULL, \n\treasoning TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tforecast_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tverified BOOLEAN NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_forecasts_forecast_time ON incident_forecasts (forecast_time);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_forecasts_created_at ON incident_forecasts (created_at);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_forecasts_cluster_id ON incident_forecasts (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS incidents (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\troot_cause TEXT, \n\troot_service VARCHAR(253), \n\tconfidence_score FLOAT, \n\taffected_services_json TEXT, \n\tcascade_chain_json TEXT, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incidents_status ON incidents (status);')
    op.execute('CREATE TABLE IF NOT EXISTS infrastructure_scores (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tcluster_health FLOAT NOT NULL, \n\tnamespace_health FLOAT NOT NULL, \n\tservice_health FLOAT NOT NULL, \n\tdependency_health FLOAT NOT NULL, \n\tincident_risk_score FLOAT NOT NULL, \n\trecovery_readiness_score FLOAT NOT NULL, \n\tai_confidence_score FLOAT NOT NULL, \n\toperational_stability_score FLOAT NOT NULL, \n\tcascading_failure_probability FLOAT NOT NULL, \n\toverall_health FLOAT NOT NULL, \n\tnamespace_scores_json TEXT NOT NULL, \n\tservice_scores_json TEXT NOT NULL, \n\tcalculated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_scores_cluster_id ON infrastructure_scores (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_scores_calculated_at ON infrastructure_scores (calculated_at);')
    op.execute('CREATE TABLE IF NOT EXISTS infrastructure_timelines (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tevent_id UUID NOT NULL, \n\tparent_event_id UUID, \n\tevent_type VARCHAR(64) NOT NULL, \n\tsource_entity VARCHAR(253) NOT NULL, \n\taffected_entities TEXT NOT NULL, \n\tcausality_score FLOAT NOT NULL, \n\tlineage_depth INTEGER NOT NULL, \n\tmetadata_json TEXT NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_timelines_timestamp ON infrastructure_timelines (timestamp);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_timelines_event_id ON infrastructure_timelines (event_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_infrastructure_timelines_cluster_id ON infrastructure_timelines (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS k8s_resource_intelligence (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tnamespace VARCHAR(253) NOT NULL, \n\tresource_type VARCHAR(64) NOT NULL, \n\tpressure_type VARCHAR(64) NOT NULL, \n\tpressure_score FLOAT NOT NULL, \n\tsaturation_percent FLOAT NOT NULL, \n\taffected_workloads TEXT NOT NULL, \n\tmitigation_json TEXT NOT NULL, \n\tdetected_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_k8s_resource_intelligence_detected_at ON k8s_resource_intelligence (detected_at);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_k8s_resource_intelligence_namespace ON k8s_resource_intelligence (namespace);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_k8s_resource_intelligence_cluster_id ON k8s_resource_intelligence (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS pods (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tnamespace VARCHAR(128) NOT NULL, \n\tname VARCHAR(253) NOT NULL, \n\tnode_name VARCHAR(253), \n\tphase VARCHAR(32) NOT NULL, \n\towner_kind VARCHAR(64), \n\towner_name VARCHAR(253), \n\tlabels_json TEXT, \n\trestart_count INTEGER NOT NULL, \n\tcpu_limit_millicores INTEGER, \n\tmemory_limit_bytes INTEGER, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_pods_namespace ON pods (namespace);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_pods_name ON pods (name);')
    op.execute('CREATE TABLE IF NOT EXISTS service_health_scores (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tservice_name VARCHAR(253) NOT NULL, \n\tuptime_score FLOAT NOT NULL, \n\tstability_score FLOAT NOT NULL, \n\tdependency_score FLOAT NOT NULL, \n\tresource_score FLOAT NOT NULL, \n\toverall_health FLOAT NOT NULL, \n\trisk_level VARCHAR(32) NOT NULL, \n\trestart_frequency FLOAT NOT NULL, \n\tincident_frequency FLOAT NOT NULL, \n\trecovery_time_avg_seconds FLOAT NOT NULL, \n\tcalculated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_service_health_scores_service_name ON service_health_scores (service_name);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_service_health_scores_calculated_at ON service_health_scores (calculated_at);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_service_health_scores_cluster_id ON service_health_scores (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS topology_edges (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\ttopology_version_id UUID NOT NULL, \n\tsource_node_id VARCHAR(512) NOT NULL, \n\ttarget_node_id VARCHAR(512) NOT NULL, \n\tedge_type VARCHAR(64) NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\tdiscovery_method VARCHAR(64) NOT NULL, \n\thealth VARCHAR(32) NOT NULL, \n\tmetadata_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(topology_version_id) REFERENCES topology_versions (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_edges_source_node_id ON topology_edges (source_node_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_edges_topology_version_id ON topology_edges (topology_version_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_edges_target_node_id ON topology_edges (target_node_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_edges_cluster_id ON topology_edges (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS topology_nodes (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\ttopology_version_id UUID NOT NULL, \n\tnode_id VARCHAR(512) NOT NULL, \n\tnamespace VARCHAR(128) NOT NULL, \n\tkind VARCHAR(64) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\thealth VARCHAR(32) NOT NULL, \n\tlabels_json TEXT, \n\tmetadata_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(topology_version_id) REFERENCES topology_versions (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_nodes_namespace ON topology_nodes (namespace);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_nodes_cluster_id ON topology_nodes (cluster_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_nodes_node_id ON topology_nodes (node_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_nodes_topology_version_id ON topology_nodes (topology_version_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_topology_nodes_kind ON topology_nodes (kind);')
    op.execute('CREATE TABLE IF NOT EXISTS ai_confidence_validations (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\trca_reasoning TEXT NOT NULL, \n\tconfidence_score FLOAT NOT NULL, \n\tvalidation_checks_json TEXT NOT NULL, \n\tpassed_checks INTEGER NOT NULL, \n\tfailed_checks INTEGER NOT NULL, \n\tis_hallucination BOOLEAN NOT NULL, \n\tis_valid BOOLEAN NOT NULL, \n\tvalidation_details_json TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_confidence_validations_incident_id ON ai_confidence_validations (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS ai_insights (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tagent_type VARCHAR(64) NOT NULL, \n\tinsight_type VARCHAR(64) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tcontent TEXT NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\treasoning TEXT, \n\tmetadata_json TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_insights_agent_type ON ai_insights (agent_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_insights_incident_id ON ai_insights (incident_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_insights_agent_type ON ai_insights (agent_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_insights_incident_id ON ai_insights (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS ai_reasoning_logs (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tagent_type VARCHAR(64) NOT NULL, \n\tprompt TEXT NOT NULL, \n\tresponse TEXT NOT NULL, \n\ttokens_used INTEGER NOT NULL, \n\tlatency_ms INTEGER NOT NULL, \n\tmodel_used VARCHAR(128) NOT NULL, \n\tsuccess BOOLEAN NOT NULL, \n\terror_message TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_reasoning_logs_incident_id ON ai_reasoning_logs (incident_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_reasoning_logs_agent_type ON ai_reasoning_logs (agent_type);')
    op.execute('CREATE TABLE IF NOT EXISTS ai_recommendations (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tagent_type VARCHAR(64) NOT NULL, \n\tpriority INTEGER NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tdescription TEXT NOT NULL, \n\taction_type VARCHAR(64) NOT NULL, \n\tkubectl_command TEXT, \n\tconfidence FLOAT NOT NULL, \n\trisk_score FLOAT NOT NULL, \n\tblast_radius_impact VARCHAR(32) NOT NULL, \n\treasoning TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_recommendations_incident_id ON ai_recommendations (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS incident_ancestry (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\troot_incident_id UUID NOT NULL, \n\tancestry_depth INTEGER NOT NULL, \n\tamplification_factor FLOAT NOT NULL, \n\tevolution_chain_json TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(root_incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_ancestry_incident_id ON incident_ancestry (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS incident_events (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tevent_id UUID NOT NULL, \n\tstream_message_id VARCHAR(64), \n\tevent_type VARCHAR(64) NOT NULL, \n\tpayload_json TEXT, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_events_timestamp ON incident_events (timestamp);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_events_incident_id ON incident_events (incident_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_events_event_id ON incident_events (event_id);')
    op.execute('CREATE TABLE IF NOT EXISTS incident_summaries (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\texecutive_summary TEXT NOT NULL, \n\ttechnical_explanation TEXT NOT NULL, \n\ttimeline_summary TEXT NOT NULL, \n\timpact_analysis TEXT NOT NULL, \n\tremediation_steps TEXT NOT NULL, \n\tgenerated_by VARCHAR(128) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_summaries_incident_id ON incident_summaries (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS incident_timeline (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tdescription TEXT, \n\tsource VARCHAR(128), \n\tseverity VARCHAR(32) NOT NULL, \n\tmetadata_json TEXT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_timeline_timestamp ON incident_timeline (timestamp);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_incident_timeline_incident_id ON incident_timeline (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS pod_metrics (\n\tid UUID NOT NULL, \n\tpod_id UUID NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcpu_usage_millicores FLOAT, \n\tmemory_usage_bytes FLOAT, \n\tcpu_percent FLOAT, \n\tmemory_percent FLOAT, \n\tnetwork_rx_bytes FLOAT, \n\tnetwork_tx_bytes FLOAT, \n\tdisk_usage_bytes FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(pod_id) REFERENCES pods (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_pod_metrics_pod_id ON pod_metrics (pod_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_pod_metrics_timestamp ON pod_metrics (timestamp);')
    op.execute('CREATE TABLE IF NOT EXISTS recommendations (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tagent_type VARCHAR(64) NOT NULL, \n\tpriority INTEGER NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tdescription TEXT NOT NULL, \n\taction_type VARCHAR(64) NOT NULL, \n\tkubectl_command TEXT, \n\tconfidence FLOAT NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_recommendations_incident_id ON recommendations (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS remediation_orchestrations (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tworkflow_json TEXT NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tstep_count INTEGER NOT NULL, \n\tcompleted_steps INTEGER NOT NULL, \n\trollback_required BOOLEAN NOT NULL, \n\tconfidence_score FLOAT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_remediation_orchestrations_incident_id ON remediation_orchestrations (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS replay_frames (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tframe_index INTEGER NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tevent_count INTEGER NOT NULL, \n\ttopology_state_json TEXT, \n\tevents_json TEXT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_frames_incident_id ON replay_frames (incident_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_frames_timestamp ON replay_frames (timestamp);')
    op.execute('CREATE TABLE IF NOT EXISTS simulated_incidents (\n\tid UUID NOT NULL, \n\tcluster_id UUID NOT NULL, \n\tincident_id UUID, \n\tsimulation_type VARCHAR(64) NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\tnamespace VARCHAR(253) NOT NULL, \n\ttarget_pods TEXT NOT NULL, \n\ttarget_services TEXT NOT NULL, \n\tduration_seconds INTEGER NOT NULL, \n\tcascading_probability FLOAT NOT NULL, \n\tmetadata_json TEXT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(cluster_id) REFERENCES clusters (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_simulated_incidents_simulation_type ON simulated_incidents (simulation_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_simulated_incidents_cluster_id ON simulated_incidents (cluster_id);')
    op.execute('CREATE TABLE IF NOT EXISTS blast_radius_events (\n\tid UUID NOT NULL, \n\tsimulation_id UUID NOT NULL, \n\torigin_pod VARCHAR(253) NOT NULL, \n\torigin_namespace VARCHAR(253) NOT NULL, \n\taffected_services TEXT NOT NULL, \n\tpropagation_depth INTEGER NOT NULL, \n\tdegradation_intensity FLOAT NOT NULL, \n\trecovery_path_json TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(simulation_id) REFERENCES simulated_incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_blast_radius_events_simulation_id ON blast_radius_events (simulation_id);')
    op.execute('CREATE TABLE IF NOT EXISTS recovery_timelines (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tsimulation_id UUID, \n\tevent_type VARCHAR(64) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tdescription TEXT NOT NULL, \n\taffected_services TEXT NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\trecovery_estimate_seconds INTEGER NOT NULL, \n\tactual_recovery_seconds INTEGER, \n\tstatus VARCHAR(32) NOT NULL, \n\tmetadata_json TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(simulation_id) REFERENCES simulated_incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_recovery_timelines_event_type ON recovery_timelines (event_type);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_recovery_timelines_incident_id ON recovery_timelines (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS remediation_actions (\n\tid UUID NOT NULL, \n\tsimulation_id UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\taction_type VARCHAR(64) NOT NULL, \n\ttarget_pod VARCHAR(253), \n\ttarget_service VARCHAR(253), \n\ttarget_namespace VARCHAR(253) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tai_recommendation TEXT NOT NULL, \n\tparameters_json TEXT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(simulation_id) REFERENCES simulated_incidents (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_remediation_actions_simulation_id ON remediation_actions (simulation_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_remediation_actions_incident_id ON remediation_actions (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS replay_events (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tframe_id UUID, \n\tevent_id UUID NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\tseverity VARCHAR(32) NOT NULL, \n\tsource VARCHAR(128) NOT NULL, \n\tpayload_json TEXT, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(frame_id) REFERENCES replay_frames (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_events_event_id ON replay_events (event_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_events_frame_id ON replay_events (frame_id);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_events_timestamp ON replay_events (timestamp);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_events_incident_id ON replay_events (incident_id);')
    op.execute('CREATE TABLE IF NOT EXISTS replay_sessions (\n\tid UUID NOT NULL, \n\tincident_id UUID NOT NULL, \n\tsimulation_id UUID, \n\tframes_count INTEGER NOT NULL, \n\tduration_seconds INTEGER NOT NULL, \n\tframes_json TEXT NOT NULL, \n\ttimeline_json TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(simulation_id) REFERENCES simulated_incidents (id)\n);')
    op.execute('CREATE INDEX IF NOT EXISTS ix_replay_sessions_incident_id ON replay_sessions (incident_id);')

def downgrade() -> None:
    op.execute('DROP TABLE IF EXISTS replay_sessions CASCADE;')
    op.execute('DROP TABLE IF EXISTS replay_events CASCADE;')
    op.execute('DROP TABLE IF EXISTS remediation_actions CASCADE;')
    op.execute('DROP TABLE IF EXISTS recovery_timelines CASCADE;')
    op.execute('DROP TABLE IF EXISTS blast_radius_events CASCADE;')
    op.execute('DROP TABLE IF EXISTS simulated_incidents CASCADE;')
    op.execute('DROP TABLE IF EXISTS replay_frames CASCADE;')
    op.execute('DROP TABLE IF EXISTS remediation_orchestrations CASCADE;')
    op.execute('DROP TABLE IF EXISTS recommendations CASCADE;')
    op.execute('DROP TABLE IF EXISTS pod_metrics CASCADE;')
    op.execute('DROP TABLE IF EXISTS incident_timeline CASCADE;')
    op.execute('DROP TABLE IF EXISTS incident_summaries CASCADE;')
    op.execute('DROP TABLE IF EXISTS incident_events CASCADE;')
    op.execute('DROP TABLE IF EXISTS incident_ancestry CASCADE;')
    op.execute('DROP TABLE IF EXISTS ai_recommendations CASCADE;')
    op.execute('DROP TABLE IF EXISTS ai_reasoning_logs CASCADE;')
    op.execute('DROP TABLE IF EXISTS ai_insights CASCADE;')
    op.execute('DROP TABLE IF EXISTS ai_confidence_validations CASCADE;')
    op.execute('DROP TABLE IF EXISTS topology_nodes CASCADE;')
    op.execute('DROP TABLE IF EXISTS topology_edges CASCADE;')
    op.execute('DROP TABLE IF EXISTS service_health_scores CASCADE;')
    op.execute('DROP TABLE IF EXISTS pods CASCADE;')
    op.execute('DROP TABLE IF EXISTS k8s_resource_intelligence CASCADE;')
    op.execute('DROP TABLE IF EXISTS infrastructure_timelines CASCADE;')
    op.execute('DROP TABLE IF EXISTS infrastructure_scores CASCADE;')
    op.execute('DROP TABLE IF EXISTS incidents CASCADE;')
    op.execute('DROP TABLE IF EXISTS incident_forecasts CASCADE;')
    op.execute('DROP TABLE IF EXISTS executive_metrics CASCADE;')
    op.execute('DROP TABLE IF EXISTS topology_versions CASCADE;')
    op.execute('DROP TABLE IF EXISTS topology_snapshots CASCADE;')
    op.execute('DROP TABLE IF EXISTS services CASCADE;')
    op.execute('DROP TABLE IF EXISTS infrastructure_memory CASCADE;')
    op.execute('DROP TABLE IF EXISTS dependency_scores CASCADE;')
    op.execute('DROP TABLE IF EXISTS dependency_edges CASCADE;')
    op.execute('DROP TABLE IF EXISTS correlation_groups CASCADE;')
    op.execute('DROP TABLE IF EXISTS clusters CASCADE;')
    op.execute('DROP TABLE IF EXISTS anomaly_patterns CASCADE;')
